config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'books/index'
  get 'books/create'
  get 'books/new'
  get 'books/edit'
  get 'books/show'
  get 'books/update'
  get 'books/destroy'
  get 'spells/index'
  get 'spells/create'
  get 'spells/new'
  get 'spells/edit'
  get 'spells/show'
  get 'spells/update'
  get 'spells/destroy'
  get "delete_spell_from_book", to: "books#delete_spell_from_book"
  get "add_spell_to_book", to: "books#add_spell_to_book"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :spells, :books, :spellbooks
    root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_and_belongs_to_many :spells
    
    validates_presence_of :name
    
    def self.select_books
        books_arr = []
        Book.order(:name).each do |b|
            if books_arr.include?(b.name) == false
                books_arr.push [b.name, b.id]
            end
        end
        return books_arr
    end
end

app/models/spell.rb
class Spell < ApplicationRecord
    has_and_belongs_to_many :books
    has_many :spellclasses

    validates_presence_of :name, :level, :school, :description

    #scope :filter_by_level, -> (level) {where level: level}
    #scope :filter_by_school, -> (school) {where school: school}
    #scope :filter_by_concentration, -> (concentration) {where concentration: concentration}

    def self.order_by
        return Spell.order(:level, :name)
    end

    def self.school_select
         schools = []
         schools << ""
         Spell.order(:school).each do |spell|
           if schools.include?(spell.school) == false
             schools << spell.school
           end
         end
         return schools
    end

    def self.all_levels
      spell_levels = []
      Spell.order(:level).each do |spell|
        if spell_levels.include?(spell.level) == false
          spell_levels << spell.level
        end
      end
      return spell_levels
    end

    def self.all_schools
      spell_schools = []
      Spell.order(:school).each do |spell|
        if spell_schools.include?(spell.school) == false
          spell_schools << spell.school
        end
      end
      return spell_schools
    end
    # accepts_nested_attributes_for :spellclasses
end

app/models/spellclass.rb
class Spellclass < ApplicationRecord
    belongs_to :spell
    
    def self.select_all
        classes = []
        Spellclass.order(:spellclasses).each do |c|
            if classes.include?(c) == false
                classes << c
            end
        end
        return classes
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
      @books = Book.all
  end

  def create
      @book = Book.new(book_params)
      Book.all.each do |b|
          if b.name.downcase == @book.name.downcase
              flash[:notice] = "#{@book.name} already exists"
              render :new
              return
          end
      end
      if @book.save
          flash[:notice] = "Successfully added #{@book.name} to All Books"
          redirect_to books_path
      else
          flash[:notice] = "Book name cannot be blank"
          render :new
      end
  end

  def new
      @book = Book.new
  end

  def edit
      @spell = Spell.find(params[:id])
  end

  def show
      @book = Book.find(params[:id])
      @spells = @book.spells
  end

  def update
  end

  def destroy
      @book = Book.find(params[:id])
      if @book.destroy
          flash[:notice] = "#{@book.name} is succesfully deleted"
      else
          flash[:notice] = "Please try delete again"
      end
      redirect_to books_path
  end

  def delete_spell_from_book
      @book = Book.find(params[:b_id])
      @spell = Spell.find(params[:s_id])
      if @book.spells.destroy(@spell)
          flash[:notice] = "#{@spell.name} is deleted from #{@book.name}."
      else
          flash[:notice] = "Try delete the spell again"
      end
      redirect_to books_path
  end

  def add_spell_to_book
      @spell = Spell.find(params[:spell_id])
      @book = Book.find(params[:book_id])
      if @book.spells.include?(@spell)
          flash[:notice] = "#{@spell.name} already exists in #{@book.name}"
          render :edit
          return
      end
      if @book.spells.append(@spell)
          flash[:notice] = "Added #{@spell.name} to #{@book.name}."
      else
          flash[:notice] = "Try again"
      end
      redirect_to books_path
  end

  private
    def book_params
        params.require(:book).permit(:name)
    end

    def spell_params
        params.require(:spell).permit(:name, :level, :school, :concentration, :description, :spellclasses)
    end
end

app/controllers/spellbooks_controller.rb
class SpellbooksController < ApplicationController
  def index
  end

  def create
  end

  def new
      @book = Book.find(params[:b_id])
      @spells = Spell.all
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  def index
      @spells = Spell.order_by
      @spellclasses = Spellclass.all
  end

  def create
      @spell = Spell.new(spell_params)
      Spell.all.each do |s|
          if s.name.downcase == @spell.name.downcase
              flash[:notice] = "Spell name cannot be the same as an existing spell"
              render :new
              return
          end
      end
      if @spell.name == ""
          flash[:notice] = "Spell name cannot be blank"
          render :new
          return
      elsif @spell.school == ""
          flash[:notice] = "Spell school cannot be blank"
          render :new
          return
      elsif @spell.description == ""
          flash[:notice] = "Description cannot be blank"
          render :new
          return
      end
      if @spell.save
          flash[:notice] = "Successfully added #{@spell.name} to All Spells"
          redirect_to spells_path
      else
          flash[:notice] = "An error has occurred"
          render :new
      end
  end

  def new
      @spell = Spell.new
  end

  def edit
      @spell = Spell.find(params[:id])
  end

  def show
      @spell = Spell.find(params[:id])
  end

  def update
      @spell = Spell.find(params[:id])
      if @spell.update(spell_params)
          flash[:notice] = "Successfully edited #{@spell.name}"
          redirect_to spells_path
      else
          flash[:notice] = "Please try edit again"
          render :edit
      end
  end

  def destroy
      @spell = Spell.find(params[:id])
      if @spell.destroy
          flash[:notice] = "#{@spell.name} is successfully deleted"
          redirect_to spells_path
      else
          flash[:notice] = "Please try delete again"
          render :edit
      end
  end

  private
    def spell_params
        params.require(:spell).permit(:name, :level, :school, :concentration, :description, :spellclasses)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/spellbooks_helper.rb
module SpellbooksHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_filter_form.html.erb
<%= form_with(local: true, method: "get", :url => books_show_path) do |form| %>

<div>
  <%= form.label "Levels: " %>
  <% Spell.all_levels.each do |level| %>
    <%= form.label level %>
    <%= form.check_box :level => level %>
  <% end %>
</div>

<div>
  <%= form.label "School: " %>
  <% Spell.all_schools.each do |school| %>
    <%= form.label school %>
    <%= form.check_box :school => school %>
  <% end %>
<div>

<div>
  <%= form.label "Concentration" %>
  <%= form.label "Yes" %>
  <%= form.check_box :concentration => "Yes" %>
  <%= form.label "No" %>
  <%= form.check_box :concentration => "No" %>
</div>
  <%= form.hidden_field :id, :value => @book.id %>
  <%= form.submit "Apply filter" %>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: @book, local: true) do |form| %>

<div>
  <h3>
    <%= form.label "Name: " %>
    <%= form.text_field :name %>
  </h3>
</div>

<div>
  <h3>
    <%= form.submit "Submit", :class => "button btn btn-default btn-lg" %>
  </h3>
</div>

<% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<body>
  <header>
      <h1 class = "logo">Add <%= @spell.name%> to Book</h1>
      <nav>
        <ul>
          <li> <%= link_to "All Spells", spells_path %> </li>
          <li> <%= link_to "Home", root_path %> </li>
        </ul>
      </nav>
  </header>

  <h2 class = "top"> <%= flash[:notice] %> </h2>

  <%= form_with(local: true, method: :get, :url => add_spell_to_book_path) do |form| %>
  <div class = "top">
    <h2>
        <%= form.label "Select a book: " %>
        <%= form.select(:book_id, Book.select_books) %>
    </h2>
  </div>
      <%= form.hidden_field :spell_id, :value => @spell.id %>
  <div>
      <%= form.submit "Submit", :class => "button btn btn-default btn-lg" %>
  </div>
  <% end %>
</body>

app/views/books/index.html.erb
<body>
  <header>
      <h1 class = "logo">All Books</h1>
      <nav>
        <ul>
          <li> <%= link_to "Home", root_path%> </li>
          <li> <%= link_to "Create New", new_book_path%> </li>
        </ul>
      </nav>
  </header>

  <h2 class = "top"><%= flash[:notice]%></h2>

  <table class = "book-table">
      <tr>
          <th>Spell Count: </th>
          <th>Title:</th>
      </tr>

      <% @books.each do |book| %>
      <tr>
          <td><%= book.spells.count %></td>
          <td><%= link_to book.name, book%></td>
          <td><button><%= link_to 'Delete Book', books_destroy_path(:id => book.id) %></button></td>
      </tr>
      <% end %>
  </table>
</body>

app/views/books/new.html.erb
<body>
  <header>
      <h1 class = "logo"> New Book</h1>
      <nav>
        <ul>
          <li> <%= link_to "All Books", books_path %>  </li>
          <li> <%= link_to "Home", root_path %> </li>
        </ul>
      </nav>
  </header>

  <h2 class = "top"> <%= flash[:notice] %> </h2>
  <h2 class = "top"> Enter a new book: </h2>
  <%= render 'form', book: @book %>
</body>

app/views/books/show.html.erb
<body>
  <header>
      <h1 class = "logo"><%= @book.name %></h1>
      <nav>
        <ul>
          <li> <%= link_to "All Books", books_path %>  </li>
          <li> <%= link_to "Home", root_path %> </li>
        </ul>
      </nav>
  </header>

  <h2 class = "top"> <%= flash[:notice] %> </h2>

  <table class = "show-spells">
      <% @spells.each do |spell| %>
      <tr>
          <td>
              <%= spell.name %>
          </td>
          <td>
              <button><%= link_to "Remove Spell", delete_spell_from_book_path(:b_id => @book.id, :s_id => spell.id) %></button>
          </td>
      </tr>
      <% end %>
  </table>

  <div>
    <button> <%= link_to "Add Spell", new_spellbook_path(:b_id => @book.id) %> </button>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D&D</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spellbooks/create.html.erb
<h1>Spellbooks#create</h1>
<p>Find me in app/views/spellbooks/create.html.erb</p>

app/views/spellbooks/destroy.html.erb
<h1>Spellbooks#destroy</h1>
<p>Find me in app/views/spellbooks/destroy.html.erb</p>

app/views/spellbooks/index.html.erb
<h1>Spellbooks#index</h1>
<p>Find me in app/views/spellbooks/index.html.erb</p>

app/views/spellbooks/new.html.erb
<body>
  <header>
      <h1 class = "logo">Add Spell to <%= @book.name %></h1>
      <nav>
        <ul>
          <li> <%= link_to "Back to Books" , books_path %></li>
          <li> <%= link_to "Home", root_path %> </li>
        </ul>
      </nav>
  </header>

  <table>
      <% Spell.order(:name).each do |spell| %>
      <tr>
          <td>
              <%= spell.name %>
          </td>
          <td>
              <% if @book.spells.include?(spell) %>
                  <%= "Already in book" %>
              <% else %>
            <button>
                  <%= link_to "Add to Book", add_spell_to_book_path(:book_id => @book.id, :spell_id => spell.id) %>
              <% end %>
            </button>
          </td>
      </tr>
      <% end %>
  </table>
</body>

app/views/spellbooks/show.html.erb
<h1>Spellbooks#show</h1>
<p>Find me in app/views/spellbooks/show.html.erb</p>

app/views/spells/_form.html.erb
<%= form_with(model: @spell, local: true) do |form| %>
    <div class = "form">
      <h3>
        <%= form.label "Level: " %>
        <%= form.select :level, (0..9) %>
      </h3>
    </div>

    <div class = "form">
      <h3>
        <%= form.label "Name: " %>
        <%= form.text_field :name %>
      </h3>
    </div>

    <div class = "form">
      <h3>
        <%= form.label "School: " %>
        <%= form.select(:school, Spell.school_select)%>
      </h3>
    </div>

    <div class = "form">
      <h3>
        <%= form.label "Concentration: "%>
        <%= form.radio_button(:concentration, true) %>
        <%= form.label(:concentration, "Yes", :value => "true") %>
        <%= form.radio_button(:concentration, false)%>
        <%= form.label(:concentration, "No", :value => "false")%>
      </h3>
    </div>

    <div class = "form">
      <h3>
        <%= form.label "Description: "%> <br> </br>
        <%= form.text_area :description, :size => "33"%>
      </h3>
    </div>

    <div class = "actions">
      <h3>
        <%= form.submit "Submit", :class => "button btn btn-default btn-lg" %>
      </h3>
    </div>
<% end %>

app/views/spells/create.html.erb
<h1>Create</h1>

app/views/spells/destroy.html.erb
<h1>Spells#destroy</h1>
<p>Find me in app/views/spells/destroy.html.erb</p>

app/views/spells/edit.html.erb
<body>
  <header>
      <h1 class = "logo">Edit <%= @spell.name %></h1>
      <nav>
        <ul>
          <li> <%= link_to "All Spells", spells_path %> </li>
          <li> <%= link_to "Home", root_path %> </li>
        </ul>
      </nav>
  </header>

  <h2 class = "top"> <%= flash[:notice]%> </h2>

  <h2> Fields of <%= @spell.name %> </h2>

  <%= render 'form', spell: @spell%>
</body>

app/views/spells/index.html.erb
<body>
  <header>
      <h1 class = "logo">All Spells</h1>
      <nav>
        <ul>
          <li> <%= link_to "Home", root_path%> </li>
          <li> <%= link_to "Create New", new_spell_path%> </li>
        </ul>
      </nav>
  </header>

  <h2 class = "top"><%= flash[:notice]%></h2>

  <table class = "spell-table">
      <tr>
          <th>Name:</th>
          <th>Level:</th>
          <th>School:</th>
          <th>Concentration:</th>
      </tr>
      <% @spells.each do |spell| %>
      <tr>
          <td><%= link_to spell.name, spell%></td>
          <td><%= spell.level %></td>
          <td><%= spell.school %></td>
          <td>
              <% if spell.concentration == true %>
                  <%= "Yes" %>
              <% else %>
                  <%= "No" %>
              <% end %>
          </td>
          <td><button><%= link_to "Edit", edit_spell_path(spell) %></button></td>
          <td><button><%= link_to "Add to Book", edit_book_path(:id => spell.id)%></button></td>
          <td><button><%= link_to "Delete", spells_destroy_path(:id => spell.id)%> </button></td>
      </tr>
      <% end %>
  </table>
</body>

app/views/spells/new.html.erb
<body>
  <header>
      <h1 class = "logo"> New Spell</h1>
      <nav>
        <ul>
          <li> <%= link_to "All Spells", spells_path %> </li>
          <li> <%= link_to "Home", root_path %> </li>
        </ul>
      </nav>
  </header>

  <h2 class = "top"><%= flash[:notice]%></h2>
  <h2 class = "top"> Fields for a new spell: </h2>
  <%= render 'form', spell: @spell %>
</body>

app/views/spells/show.html.erb
<body>

  <header>
      <h1 class = "logo"><%= @spell.name %></h1>
      <nav>
        <ul>
          <li> <%= link_to "All Spells", spells_path %> </li>
          <li> <%= link_to "Home", root_path %> </li>
        </ul>
      </nav>
  </header>

  <table class = "container" id = "spell-description">
      <tr>
          <td>Level:</td>
          <td><%= @spell.level %></td>
      </tr>
      <tr>
          <td>School:</td>
          <td><%= @spell.school %></td>
      </tr>
      <tr>
          <td>Concentration:</td>
          <td>
              <% if @spell.concentration == true %>
                  <%= "Yes" %>
              <% else %>
                  <%= "No" %>
              <% end %>
          </td>
      </tr>
      <tr>
          <td>Description: </td>
          <td><%= @spell.description %></td>
      </tr>
  </table>

  <div>
    <button><%= link_to "Add #{@spell.name} to Book", edit_book_path(:id => @spell.id)%></button>
  </div>

</body>

app/views/spells/update.html.erb
<h1>update</h1>

app/views/static_pages/home.html.erb
<body class = "home">
  <h1> Dungeons & Dragons </h1>
  <h2><%= link_to "All Spells", spells_path(order_by: 'title')%></h2>
  <h2><%= link_to "All Books", books_path %></h2>
</body>